name: env_tfds_build
channels:
  - conda-forge
  - nvidia
  - pkgs/main
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - antlr-python-runtime=4.9.3
  - astunparse=1.6.3
  - async-timeout=5.0.1
  - attrs=24.3.0
  - blas=1.0
  - blinker=1.9.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - cachetools=5.3.3
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=41.0.3
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.55
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - dill=0.3.9
  - dm-tree=0.1.7
  - etils=1.10.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - flatbuffers=24.3.25
  - freetype=2.12.1
  - frozenlist=1.5.0
  - gast=0.4.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - h5py=3.12.1
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.7
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - jpeg=9e
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcurl=8.2.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.52.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.1.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - ocl-icd=2.3.2
  - omegaconf=2.3.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=24.2
  - pillow=11.0.0
  - pip=24.2
  - promise=2.3
  - propcache=0.2.0
  - protobuf=3.20.3
  - psutil=6.1.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.10.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-flatbuffers=24.3.25
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scipy=1.15.1
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.12.0
  - tensorflow-base=2.12.0
  - tensorflow-datasets=4.8.3
  - tensorflow-estimator=2.12.0
  - tensorflow-metadata=1.16.1
  - termcolor=2.1.0
  - tk=8.6.14
  - toml=0.10.2
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - werkzeug=3.1.3
  - wheel=0.44.0
  - wrapt=1.17.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - decord==0.6.0
    - easydict==1.13
    - einops==0.8.0
    - matplotlib==3.10.0
    - mediapy==1.2.2
    - opencv-python==4.11.0.86
    - pypcd==0.1.3
    - xformers==0.0.29.post1

